language : shell

env:
  - CONDA_PYTHON=3.5
  - CONDA_PYTHON=3.6
  - CONDA_PYTHON=3.7
  - CONDA_PYTHON=3.9

os :
- windows

cache :
  directories:
    - /c/tools/miniconda3
    - /c/Users/travis/AppData/Roaming/pyinstaller
    - /c/Users/travis/AppData/Local/pip/cache
    - /c/Users/travis/AppData/Local/Temp/chocolatey

install:
  - MINICONDA_PATH=/c/tools/miniconda3;
  - MINICONDA_SUB_PATH=$MINICONDA_PATH/Scripts;
  - PYTHON_ENV=$MINICONDA_PATH/envs/$CONDA_PYTHON;
  - if [[ -d $MINICONDA_SUB_PATH ]]; then
      echo "miniconda for Windows already installed";
    else
      echo "installing miniconda for windows";
      choco install -y miniconda3;
    fi;
  - export PATH="$MINICONDA_PATH:$MINICONDA_SUB_PATH:$PATH";
  - choco install -y openssl.light;
  - hash -r;
  - python -V
  - conda info -a
  - conda config --set always_yes yes --set changeps1 no;
  - conda update -q conda;
  - conda create -n $CONDA_PYTHON python=$CONDA_PYTHON
  - $PYTHON_ENV/python.exe -V
  - $PYTHON_ENV/python.exe -m pip install --upgrade pip
  - $PYTHON_ENV/Scripts/pip.exe install -U keyring netaddr ntlm-auth psutil pywin32 winkerberos futures pyinstaller

script:
  - $PYTHON_ENV/python.exe -m py_compile px.py
  - $PYTHON_ENV/python.exe px.py --help
  - $PYTHON_ENV/Scripts/pyinstaller.exe --clean --noupx -w -F -i px.ico px.py --hidden-import win32timezone --exclude-module win32ctypes
  - $PYTHON_ENV/python.exe test.py --python=$PYTHON_ENV --baseurl=https://google.com

# Deploy doesn't work due to secret $GITHUB_TOKEN requirement which is
# broken on Travis for Windows
#deploy:
#  provider: script
#  script: python tools.py --post --token=$GITHUB_TOKEN
#  on:
#    branch: master
#    condition: $CONDA_PYTHON = 3.7
